### PR TITLE
intro and register layouts

### PR DESCRIPTION
**Pull request by vuminhhieu1311**
## Related Tickets
- [#39331](https://edu-redmine.sun-asterisk.vn/issues/39331)

## WHAT (optional)
- Add Intro layout
- Add register layout
## Evidence (Screenshot or Video)
ezgif-2-07cfcee4d446
ezgif-2-f160f7da25e7

### CODE REVIEW

**Comment by vuminhhieu1311** [comment]
ready

**Comment by nvvu99** [comment]
approve

**Review by nvvu99 — APPROVED** [review]
Ok

**Comment by vuminhhieu1311** [comment]
ready

**Comment by vuminhhieu1311** [comment]
ready

**Review by huyenttm-0901 — APPROVED** [review]

**Pull request merged**
