### PR TITLE
Add account information updating feature

### PR DESCRIPTION
**Pull request by nvvu99**
## Related Tickets
- [#40171](https://edu-redmine.sun-asterisk.vn/issues/40171)

## WHAT (optional)
Add account information updating feature

## Evidence (Screenshot or Video)
Account information

### CODE REVIEW

**Review by vuminhhieu1311 — APPROVED** [review]
ok

**Comment by nvvu99** [comment]
ready

**Review by huyenttm-0901 — COMMENTED** [review]
conflict

**Comment by nvvu99** [comment]
ready

**Pull request merged**
