### PR TITLE
Change to use Repository

### PR DESCRIPTION
**Pull request by vuminhhieu1311**
## Related Tickets
- [#40951](https://edu-redmine.sun-asterisk.vn/issues/40951)

## WHAT (optional)
- Change to user repository

### CODE REVIEW

**Review by nvvu99 — APPROVED** [review]
Ok

**Comment by vuminhhieu1311** [comment]
ready

**Review by manhtd-1083 — COMMENTED** [review]
18 files change.

**Comment by vuminhhieu1311** [comment]
ready

**Review by huyenttm-0901 — APPROVED** [review]

**Pull request merged**
