### PR TITLE
Add authorization

### PR DESCRIPTION
**Pull request by vuminhhieu1311**
## Related Tickets
- [#39175](https://edu-redmine.sun-asterisk.vn/issues/39175)

## WHAT (optional)
- Authorization using gates and policies

### CODE REVIEW

**Review by nvvu99 — APPROVED** [review]
Ok

**Comment by vuminhhieu1311** [comment]
ready

**Comment by vuminhhieu1311** [comment]
ready

**Comment by vuminhhieu1311** [comment]
ready

**Comment by vuminhhieu1311** [comment]
ready

**Comment by vuminhhieu1311** [comment]
ready

**Comment by vuminhhieu1311** [comment]
ready

**Comment by vuminhhieu1311** [comment]
ready

**Review by huyenttm-0901 — APPROVED** [review]

**Pull request merged**
